export const iconsWithIds = [
    { id: '3d-g4', icon: require('@/assets/images/food-cat.png'), path: '@/assets/images/food-cat.png' },
    { id: 'a1-b2', icon: require('@/assets/images/copy-cat.png'), path: '@/assets/images/copy-cat.png' },
    { id: 'c3-d4', icon: require('@/assets/images/home-cat.png'), path: '@/assets/images/home-cat.png' },
    { id: 'e5-f6', icon: require('@/assets/images/transport-cat.png'), path: '@/assets/images/transport-cat.png' },
    { id: 'g7-h8', icon: require('@/assets/images/new-cat.png'), path: '@/assets/images/new-cat.png' },
    { id: 'i9-j0', icon: require('@/assets/images/entertainment-cat.png'), path: '@/assets/images/entertainment-cat.png' },
    { id: 'k1-l2', icon: require('@/assets/images/tools-cat.png'), path: '@/assets/images/tools-cat.png' },
    { id: 'm3-n4', icon: require('@/assets/images/new-cat.png'), path: '@/assets/images/new-cat.png' },
    { id: 'o5-p6', icon: require('@/assets/images/winner-cat.png'), path: '@/assets/images/winner-cat.png' },
    { id: 'q7-r8', icon: require('@/assets/images/important-cat.png'), path: '@/assets/images/important-cat.png' },
    { id: 's9-t0', icon: require('@/assets/images/task-cat.png'), path: '@/assets/images/task-cat.png' },
    { id: 'u1-v2', icon: require('@/assets/images/reminder-cat.png'), path: '@/assets/images/reminder-cat.png' },
    { id: 'w3-x4', icon: require('@/assets/images/diversity-cat.png'), path: '@/assets/images/diversity-cat.png' },
    { id: 'y5-z6', icon: require('@/assets/images/locate-cat.png'), path: '@/assets/images/locate-cat.png' },
    { id: 'a7-b8', icon: require('@/assets/images/clothes-cat.png'), path: '@/assets/images/clothes-cat.png' },
    { id: 'c9-d0', icon: require('@/assets/images/libs-cat.png'), path: '@/assets/images/libs-cat.png' },
    { id: 'e1-f2', icon: require('@/assets/images/stuff-cat.png'), path: '@/assets/images/stuff-cat.png' },
    { id: 'g3-h4', icon: require('@/assets/images/messages-cat.png'), path: '@/assets/images/messages-cat.png' },
    { id: 'i5-j6', icon: require('@/assets/images/finance-cat.png'), path: '@/assets/images/finance-cat.png' },
    { id: 'k7-l8', icon: require('@/assets/images/programming-cat.png'), path: '@/assets/images/programming-cat.png' },
    { id: 'm9-n0', icon: require('@/assets/images/exchange-cat.png'), path: '@/assets/images/exchange-cat.png' },
    { id: 'o1-p2', icon: require('@/assets/images/other-cat.png'), path: '@/assets/images/other-cat.png' },
  ];